hard coded eth-hash dependency version to get rid of version conflict errors
error: eth-hash 0.3.1 is installed but eth-hash<0.3.0,>=0.1.0a3 is required by {'eth-bloom'}